%General Mission Analysis Tool(GMAT) Script


%----------------------------------------
%---------- User-Modified Default Celestial Bodies
%----------------------------------------

Earth.EquatorialRadius = 6378.1366;
Earth.Flattening = 0.00335281310845547;

%----------------------------------------
%---------- Spacecraft
%----------------------------------------

Create Spacecraft MySat;
MySat.DateFormat = UTCModJulian;
MySat.Epoch = '{{EPOCH}}';
MySat.CoordinateSystem = EarthMJ2000Eq;
MySat.DisplayStateType = Keplerian;
MySat.SMA = {{SMA}};
MySat.ECC = {{ECC}};
MySat.INC = {{INC}};
MySat.RAAN = {{RAAN}};
MySat.AOP = {{AOP}};
MySat.TA = {{TA}};
MySat.DryMass = 850;
MySat.Cd = 2.2;
MySat.Cr = 1.8;
MySat.DragArea = 15;
MySat.SRPArea = 1;
MySat.SPADDragScaleFactor = 1;
MySat.SPADSRPScaleFactor = 1;
MySat.AtmosDensityScaleFactor = 1;
MySat.ExtendedMassPropertiesModel = 'None';
MySat.NAIFId = -100303;
MySat.NAIFIdReferenceFrame = -123456789;
MySat.OrbitColor = Red;
MySat.TargetColor = Teal;
MySat.OrbitErrorCovariance = [ 1e+70 0 0 0 0 0 ; 0 1e+70 0 0 0 0 ; 0 0 1e+70 0 0 0 ; 0 0 0 1e+70 0 0 ; 0 0 0 0 1e+70 0 ; 0 0 0 0 0 1e+70 ];
MySat.CdSigma = 1e+70;
MySat.CrSigma = 1e+70;
MySat.Id = 'SatId';
MySat.Attitude = CoordinateSystemFixed;
MySat.SPADSRPInterpolationMethod = Bilinear;
MySat.SPADSRPScaleFactorSigma = 1e+70;
MySat.SPADDragInterpolationMethod = Bilinear;
MySat.SPADDragScaleFactorSigma = 1e+70;
MySat.AtmosDensityScaleFactorSigma = 1e+70;
MySat.ModelFile = '../data/vehicle/models/aura.3ds';
MySat.ModelOffsetX = 0;
MySat.ModelOffsetY = 0;
MySat.ModelOffsetZ = 0;
MySat.ModelRotationX = 0;
MySat.ModelRotationY = 0;
MySat.ModelRotationZ = 0;
MySat.ModelScale = 3;
MySat.AttitudeDisplayStateType = 'Quaternion';
MySat.AttitudeRateDisplayStateType = 'AngularVelocity';
MySat.AttitudeCoordinateSystem = EarthMJ2000Eq;
MySat.EulerAngleSequence = '321';

%----------------------------------------
%---------- GroundStations
%----------------------------------------

{{GROUND_STATIONS}}

%----------------------------------------
%---------- ForceModels
%----------------------------------------

Create ForceModel DefaultProp_ForceModel;
DefaultProp_ForceModel.CentralBody = Earth;
DefaultProp_ForceModel.PrimaryBodies = {Earth};
DefaultProp_ForceModel.Drag = None;
DefaultProp_ForceModel.SRP = Off;
DefaultProp_ForceModel.RelativisticCorrection = Off;
DefaultProp_ForceModel.ErrorControl = RSSStep;
DefaultProp_ForceModel.GravityField.Earth.Degree = 4;
DefaultProp_ForceModel.GravityField.Earth.Order = 4;
DefaultProp_ForceModel.GravityField.Earth.StmLimit = 100;
DefaultProp_ForceModel.GravityField.Earth.PotentialFile = 'JGM2.cof';
DefaultProp_ForceModel.GravityField.Earth.TideModel = 'None';

%----------------------------------------
%---------- Propagators
%----------------------------------------

Create Propagator DefaultProp;
DefaultProp.FM = DefaultProp_ForceModel;
DefaultProp.Type = RungeKutta89;
DefaultProp.InitialStepSize = 60;
DefaultProp.Accuracy = 9.999999999999999e-12;
DefaultProp.MinStep = 0.001;
DefaultProp.MaxStep = 2700;
DefaultProp.MaxStepAttempts = 50;
DefaultProp.StopIfAccuracyIsViolated = true;

%----------------------------------------
%---------- EventLocators
%----------------------------------------

Create EclipseLocator EclipseLocator1;
EclipseLocator1.Spacecraft = MySat;
EclipseLocator1.Filename = {{ECLIPSE_OUTPUT}};
EclipseLocator1.OccultingBodies = {Earth, Luna};
EclipseLocator1.InputEpochFormat = 'TAIModJulian';
EclipseLocator1.InitialEpoch = '21545';
EclipseLocator1.StepSize = 10;
EclipseLocator1.FinalEpoch = '21545.138';
EclipseLocator1.UseLightTimeDelay = true;
EclipseLocator1.UseStellarAberration = true;
EclipseLocator1.WriteReport = true;
EclipseLocator1.RunMode = Automatic;
EclipseLocator1.UseEntireInterval = true;
EclipseLocator1.EclipseTypes = {'Umbra'};

Create ContactLocator ContactLocator1;
ContactLocator1.Target = MySat;
ContactLocator1.Filename = {{CONTACT_OUTPUT}};
ContactLocator1.InputEpochFormat = 'TAIModJulian';
ContactLocator1.InitialEpoch = '21545';
ContactLocator1.StepSize = 600;
ContactLocator1.FinalEpoch = '21545.138';
ContactLocator1.UseLightTimeDelay = true;
ContactLocator1.UseStellarAberration = true;
ContactLocator1.WriteReport = true;
ContactLocator1.RunMode = Automatic;
ContactLocator1.UseEntireInterval = true;
ContactLocator1.Observers = {{OBSERVERS_LIST}};
ContactLocator1.LightTimeDirection = Transmit;
ContactLocator1.LeftJustified = false;
ContactLocator1.ReportPrecision = 6;
ContactLocator1.ReportFormat = 'Legacy';
ContactLocator1.IntervalStepSize = 0;
ContactLocator1.ReportTimeFormat = 'UTCGregorian';

%----------------------------------------
%---------- Solvers
%----------------------------------------

Create DifferentialCorrector DC1;
DC1.ShowProgress = true;
DC1.ReportStyle = Normal;
DC1.ReportFile = 'DifferentialCorrectorDC1.data';
DC1.MaximumIterations = 25;
DC1.DerivativeMethod = ForwardDifference;
DC1.Algorithm = NewtonRaphson;

%----------------------------------------
%---------- Subscribers
%----------------------------------------

Create OpenFramesInterface DefaultOrbitView;
DefaultOrbitView.SolverIterations = Current;
DefaultOrbitView.UpperLeft = [ 0.35 0 ];
DefaultOrbitView.Size = [ 0.5535294117647059 0.8149038461538461 ];
DefaultOrbitView.RelativeZOrder = 31;
DefaultOrbitView.Maximized = false;
DefaultOrbitView.Add = {MySat, Earth, Luna, Sun};
DefaultOrbitView.View = {DefaultOrbitView_View};
DefaultOrbitView.CoordinateSystem = EarthMJ2000Eq;
DefaultOrbitView.DrawObject = [ true true true true ];
DefaultOrbitView.DrawTrajectory = [ true true true true ];
DefaultOrbitView.DrawAxes = [ false false false false ];
DefaultOrbitView.DrawXYPlane = [ false false false false ];
DefaultOrbitView.DrawLabel = [ true true true true ];
DefaultOrbitView.DrawUsePropLabel = [ false false false false ];
DefaultOrbitView.DrawCenterPoint = [ true true true true ];
DefaultOrbitView.DrawEndPoints = [ true true true true ];
DefaultOrbitView.DrawVelocity = [ false false false false ];
DefaultOrbitView.DrawGrid = [ false false false false ];
DefaultOrbitView.DrawLineWidth = [ 2 2 2 2 ];
DefaultOrbitView.DrawMarkerSize = [ 10 10 10 10 ];
DefaultOrbitView.DrawFontSize = [ 20 20 20 20 ];
DefaultOrbitView.Axes = On;
DefaultOrbitView.AxesLength = 12756.2726;
DefaultOrbitView.AxesLabels = On;
DefaultOrbitView.FrameLabel = Off;
DefaultOrbitView.XYPlane = On;
DefaultOrbitView.EclipticPlane = On;
DefaultOrbitView.EnableStars = Off;
DefaultOrbitView.StarCatalog = 'inp_StarsHYGv3.txt';
DefaultOrbitView.StarCount = 7000;
DefaultOrbitView.MinStarMag = -2;
DefaultOrbitView.MaxStarMag = 6;
DefaultOrbitView.MinStarPixels = 1;
DefaultOrbitView.MaxStarPixels = 10;
DefaultOrbitView.MinStarDimRatio = 0.5;
DefaultOrbitView.ShowPlot = true;
DefaultOrbitView.ShowToolbar = true;
DefaultOrbitView.SolverIterLastN = 1;
DefaultOrbitView.ShowVR = false;
DefaultOrbitView.PlaybackTimeScale = 3600;
DefaultOrbitView.MultisampleAntiAliasing = On;
DefaultOrbitView.MSAASamples = 2;
DefaultOrbitView.DrawFontPosition = {'Top-Right', 'Top-Right', 'Top-Right', 'Top-Right'};

Create GroundTrack DefaultGroundTrackPlot;
DefaultGroundTrackPlot.SolverIterations = Current;
DefaultGroundTrackPlot.UpperLeft = [ 0.02588235294117647 0.1682692307692308 ];
DefaultGroundTrackPlot.Size = [ 0.5600000000000001 0.8076923076923077 ];
DefaultGroundTrackPlot.RelativeZOrder = 27;
DefaultGroundTrackPlot.Maximized = false;
DefaultGroundTrackPlot.CentralBody = Earth;
DefaultGroundTrackPlot.TextureMap = '../data/graphics/texture/ModifiedBlueMarble.jpg';
DefaultGroundTrackPlot.Add = {{OBSERVERS_LIST_GT}};
DefaultGroundTrackPlot.DataCollectFrequency = 1;
DefaultGroundTrackPlot.UpdatePlotFrequency = 50;
DefaultGroundTrackPlot.NumPointsToRedraw = 0;
DefaultGroundTrackPlot.MaxPlotPoints = 20000;
DefaultGroundTrackPlot.ShowPlot = true;

%----------------------------------------
%---------- User Objects
%----------------------------------------

Create OpenFramesView DefaultOrbitView_View;
DefaultOrbitView_View.ViewFrame = CoordinateSystem;
DefaultOrbitView_View.ViewTrajectory = Off;
DefaultOrbitView_View.InertialFrame = Off;
DefaultOrbitView_View.SetDefaultLocation = On;
DefaultOrbitView_View.DefaultEye = [ 0 0 120001 ];
DefaultOrbitView_View.DefaultCenter = [ 0 0 0 ];
DefaultOrbitView_View.DefaultUp = [ 1 0 0 ];
DefaultOrbitView_View.SetCurrentLocation = Off;
DefaultOrbitView_View.FOVy = 45;


%----------------------------------------
%---------- Mission Sequence
%----------------------------------------

BeginMissionSequence;
Propagate 'Prop x sec' DefaultProp(MySat) {MySat.ElapsedSecs = 86400, OrbitColor = [255 0 0]};
