%General Mission Analysis Tool(GMAT) Script


%----------------------------------------
%---------- User-Modified Default Celestial Bodies
%----------------------------------------

Earth.EquatorialRadius = 6378.1366;
Earth.Flattening = 0.00335281310845547;

%----------------------------------------
%---------- Spacecraft
%----------------------------------------

Create Spacecraft MySat;
MySat.DateFormat = UTCModJulian;
MySat.Epoch = '{{EPOCH}}';
MySat.CoordinateSystem = EarthMJ2000Eq;
MySat.DisplayStateType = Cartesian;
MySat.X = {{X}};
MySat.Y = {{Y}};
MySat.Z = {{Z}};
MySat.VX = {{VX}};
MySat.VY = {{VY}};
MySat.VZ = {{VZ}};
MySat.DryMass = 850;
MySat.Cd = 2.2;
MySat.Cr = 1.8;
MySat.DragArea = 15;
MySat.SRPArea = 1;
MySat.SPADDragScaleFactor = 1;
MySat.SPADSRPScaleFactor = 1;
MySat.AtmosDensityScaleFactor = 1;
MySat.ExtendedMassPropertiesModel = 'None';
MySat.NAIFId = -100303;
MySat.NAIFIdReferenceFrame = -123456789;
MySat.OrbitColor = Red;
MySat.TargetColor = Teal;
MySat.OrbitErrorCovariance = [ 1e+70 0 0 0 0 0 ; 0 1e+70 0 0 0 0 ; 0 0 1e+70 0 0 0 ; 0 0 0 1e+70 0 0 ; 0 0 0 0 1e+70 0 ; 0 0 0 0 0 1e+70 ];
MySat.CdSigma = 1e+70;
MySat.CrSigma = 1e+70;
MySat.Id = 'SatId';
MySat.Attitude = CoordinateSystemFixed;
MySat.SPADSRPInterpolationMethod = Bilinear;
MySat.SPADSRPScaleFactorSigma = 1e+70;
MySat.SPADDragInterpolationMethod = Bilinear;
MySat.SPADDragScaleFactorSigma = 1e+70;
MySat.AtmosDensityScaleFactorSigma = 1e+70;
MySat.ModelFile = '../data/vehicle/models/aura.3ds';
MySat.ModelOffsetX = 0;
MySat.ModelOffsetY = 0;
MySat.ModelOffsetZ = 0;
MySat.ModelRotationX = 0;
MySat.ModelRotationY = 0;
MySat.ModelRotationZ = 0;
MySat.ModelScale = 3;
MySat.AttitudeDisplayStateType = 'Quaternion';
MySat.AttitudeRateDisplayStateType = 'AngularVelocity';
MySat.AttitudeCoordinateSystem = EarthMJ2000Eq;
MySat.EulerAngleSequence = '321';

%----------------------------------------
%---------- GroundStations
%----------------------------------------

Create GroundStation Redu;
Redu.OrbitColor = Thistle;
Redu.TargetColor = DarkGray;
Redu.CentralBody = Earth;
Redu.StateType = Spherical;
Redu.HorizonReference = Ellipsoid;
Redu.Location1 = 50.0005;
Redu.Location2 = 5.1453;
Redu.Location3 = 0.387;
Redu.Id = 'Redu';
Redu.IonosphereModel = 'None';
Redu.TroposphereModel = 'None';
Redu.DataSource = 'Constant';
Redu.Temperature = 295.1;
Redu.Pressure = 1013.5;
Redu.Humidity = 55;
Redu.MinimumElevationAngle = 7;

%----------------------------------------
%---------- ForceModels
%----------------------------------------

Create ForceModel DefaultProp_ForceModel;
DefaultProp_ForceModel.CentralBody = Earth;
DefaultProp_ForceModel.PrimaryBodies = {Earth};
DefaultProp_ForceModel.Drag = None;
DefaultProp_ForceModel.SRP = Off;
DefaultProp_ForceModel.RelativisticCorrection = Off;
DefaultProp_ForceModel.ErrorControl = RSSStep;
DefaultProp_ForceModel.GravityField.Earth.Degree = 4;
DefaultProp_ForceModel.GravityField.Earth.Order = 4;
DefaultProp_ForceModel.GravityField.Earth.StmLimit = 100;
DefaultProp_ForceModel.GravityField.Earth.PotentialFile = 'JGM2.cof';
DefaultProp_ForceModel.GravityField.Earth.TideModel = 'None';

%----------------------------------------
%---------- Propagators
%----------------------------------------

Create Propagator DefaultProp;
DefaultProp.FM = DefaultProp_ForceModel;
DefaultProp.Type = RungeKutta89;
DefaultProp.InitialStepSize = 60;
DefaultProp.Accuracy = 9.999999999999999e-12;
DefaultProp.MinStep = 0.001;
DefaultProp.MaxStep = 2700;
DefaultProp.MaxStepAttempts = 50;
DefaultProp.StopIfAccuracyIsViolated = true;

%----------------------------------------
%---------- EventLocators
%----------------------------------------

Create EclipseLocator EclipseLocator1;
EclipseLocator1.Spacecraft = MySat;
EclipseLocator1.Filename = '.\src\gmat_files\EclipseLocator.txt';
EclipseLocator1.OccultingBodies = {Earth, Luna};
EclipseLocator1.InputEpochFormat = 'TAIModJulian';
EclipseLocator1.InitialEpoch = '21545';
EclipseLocator1.StepSize = 10;
EclipseLocator1.FinalEpoch = '21545.138';
EclipseLocator1.UseLightTimeDelay = true;
EclipseLocator1.UseStellarAberration = true;
EclipseLocator1.WriteReport = true;
EclipseLocator1.RunMode = Manual;
EclipseLocator1.UseEntireInterval = true;
EclipseLocator1.EclipseTypes = {'Umbra', 'Penumbra', 'Antumbra'};

Create ContactLocator ContactLocator1;
ContactLocator1.Target = MySat;
ContactLocator1.Filename = '.\src\gmat_files\ContactLocator.txt';
ContactLocator1.InputEpochFormat = 'TAIModJulian';
ContactLocator1.InitialEpoch = '21545';
ContactLocator1.StepSize = 600;
ContactLocator1.FinalEpoch = '21545.138';
ContactLocator1.UseLightTimeDelay = true;
ContactLocator1.UseStellarAberration = true;
ContactLocator1.WriteReport = true;
ContactLocator1.RunMode = Manual;
ContactLocator1.UseEntireInterval = true;
ContactLocator1.Observers = {Redu};
ContactLocator1.LightTimeDirection = Transmit;
ContactLocator1.LeftJustified = false;
ContactLocator1.ReportPrecision = 6;
ContactLocator1.ReportFormat = 'Legacy';
ContactLocator1.IntervalStepSize = 0;
ContactLocator1.ReportTimeFormat = 'UTCGregorian';

%----------------------------------------
%---------- Solvers
%----------------------------------------

Create DifferentialCorrector DC1;
DC1.ShowProgress = true;
DC1.ReportStyle = Normal;
DC1.ReportFile = 'DifferentialCorrectorDC1.data';
DC1.MaximumIterations = 25;
DC1.DerivativeMethod = ForwardDifference;
DC1.Algorithm = NewtonRaphson;

%----------------------------------------
%---------- Subscribers
%----------------------------------------

Create OrbitView DefaultOrbitView;
GMAT DefaultOrbitView.SolverIterations = Current;
GMAT DefaultOrbitView.UpperLeft = [ 0.35 0 ];
GMAT DefaultOrbitView.Size = [ 0.5535294117647059 0.8149038461538461 ];
GMAT DefaultOrbitView.RelativeZOrder = 31;
GMAT DefaultOrbitView.Maximized = false;
GMAT DefaultOrbitView.Add = {MySat, Earth, Luna, Sun};
GMAT DefaultOrbitView.CoordinateSystem = EarthMJ2000Eq;
GMAT DefaultOrbitView.DrawObject = [ true true true true ];
GMAT DefaultOrbitView.DataCollectFrequency = 1;
GMAT DefaultOrbitView.UpdatePlotFrequency = 50;
GMAT DefaultOrbitView.NumPointsToRedraw = 0;
GMAT DefaultOrbitView.ShowPlot = true;
GMAT DefaultOrbitView.MaxPlotPoints = 20000;
GMAT DefaultOrbitView.ShowLabels = true;
GMAT DefaultOrbitView.ViewPointReference = Earth;
GMAT DefaultOrbitView.ViewPointVector = [ 0 0 120001 ];
GMAT DefaultOrbitView.ViewDirection = Earth;
GMAT DefaultOrbitView.ViewScaleFactor = 1;
GMAT DefaultOrbitView.ViewUpCoordinateSystem = EarthMJ2000Eq;
GMAT DefaultOrbitView.ViewUpAxis = X;
GMAT DefaultOrbitView.EclipticPlane = On;
GMAT DefaultOrbitView.XYPlane = On;
GMAT DefaultOrbitView.WireFrame = Off;
GMAT DefaultOrbitView.Axes = On;
GMAT DefaultOrbitView.Grid = Off;
GMAT DefaultOrbitView.SunLine = Off;
GMAT DefaultOrbitView.UseInitialView = On;
GMAT DefaultOrbitView.StarCount = 7000;
GMAT DefaultOrbitView.EnableStars = Off;
GMAT DefaultOrbitView.EnableConstellations = On;

Create GroundTrackPlot DefaultGroundTrackPlot;
GMAT DefaultGroundTrackPlot.SolverIterations = Current;
GMAT DefaultGroundTrackPlot.UpperLeft = [ 0.02588235294117647 0.1682692307692308 ];
GMAT DefaultGroundTrackPlot.Size = [ 0.5600000000000001 0.8076923076923077 ];
GMAT DefaultGroundTrackPlot.RelativeZOrder = 27;
GMAT DefaultGroundTrackPlot.Maximized = false;
GMAT DefaultGroundTrackPlot.Add = {Redu, MySat};
GMAT DefaultGroundTrackPlot.DataCollectFrequency = 1;
GMAT DefaultGroundTrackPlot.UpdatePlotFrequency = 50;
GMAT DefaultGroundTrackPlot.NumPointsToRedraw = 0;
GMAT DefaultGroundTrackPlot.ShowPlot = true;
GMAT DefaultGroundTrackPlot.MaxPlotPoints = 20000;
GMAT DefaultGroundTrackPlot.CentralBody = Earth;
GMAT DefaultGroundTrackPlot.TextureMap = '../data/graphics/texture/ModifiedBlueMarble.jpg';


%----------------------------------------
%---------- Mission Sequence
%----------------------------------------

BeginMissionSequence
Propagate 'Prop x sec' DefaultProp(MySat) {MySat.ElapsedSecs = 604800, OrbitColor = [255 0 0]};